backend:
  name: git-gateway
  branch: main

  "media_folder: "images
  "public_folder: "/images

  "locale: "fa

collections:
  - name: "pages"
    label: "صفحات"
    files:
      - label: "صفحه اصلی"
        name: "home"
        file: "content/home.json"
        fields:
          - {label: "عنوان", widget: "string", name: "title"}
          - {label: "توضیحات", widget: "text", name: "description"}
          - {label: "متن دکمه", widget: "string", name: "button_text"}
