backend:
  name: git-gateway
  identity_url: https://dev-d0etjgx4egzjlrsx.us.auth0.com
  auth_type: oauth
  client_id: BDjnKS6DrhL5ROtlSEwbkD0kUI75s0P8
  client_secret: yK7yQbmaOthVKLivHopAu0zd3q66ONiOGd9KFydJ4ofX5pxZPsVqBOGB1n22ZmHY

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "صفحات"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "بدنه", name: "body", widget: "markdown" }
